In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('메타버스 박물관 관련 인식조사 및 이용의도 설문_Rawdata_20241118_데이터.xlsx')

In [21]:
df['q1'].value_counts().sort_index().to_frame()

           count
q1
1) 5000원     100
2) 7000원     100
3) 10000원    100
4) 15000원    100
5) 20000원    100

In [69]:
def makeFrame(category):
    df2 = df[category].value_counts().sort_index().to_frame()
    print(df2)
    df2 = df2.reset_index()
    df2.columns = ['name' , 'count']
    # 전체 합계를 계산
    total_count = df2['count'].sum()
    df2['p_count'] = df2['count'] / total_count * 100
    df2['p_count'] = df2['p_count'].astype('str') + '%'
    df2['category'] = category
    return df2

In [70]:
df3 = pd.DataFrame(columns = ['category','name','count','p_count'])
categorys = df.columns[1:]
for category in categorys:
    df2 = makeFrame(category)
    df3 = pd.concat([df3,df2])

           count
q1
1) 5000원     100
2) 7000원     100
3) 10000원    100
4) 15000원    100
5) 20000원    100
       count
q4
1) 남성    198
2) 여성    302
      count
q5_1
22        1
24        3
25        3
26        3
27        2
28        5
29        8
30        6
31       11
32       10
33       10
34       12
35       18
36       20
37       17
38       23
39       14
40       22
41       26
42       30
43       36
44       26
45       26
46       29
47       19
48        7
49       14
50       18
51        7
52       12
53       10
54       16
55       14
56        5
57        5
58        4
59        8
            count
q6
1) 만20-29세     25
2) 만30-39세    141
3) 만40-49세    235
4) 만50-59세     99
          count
q7
1) 서울       130
10) 충청북도     11
11) 충청남도     15
12) 전라북도      5
13) 전라남도     10
14) 경상북도     15
15) 경상남도     26
16) 제주도       4
17) 세종        4
2) 부산        33
3) 대구        24
4) 인천        35
5) 광주        12
6) 대전        17
7) 울산         8
8) 경기도      139
9) 강원도       12
        count
q8
1) 예      418
2) 아니오     82
            count
q9
1) 세대주        306
3) 세대주 배우자    194
        count
q10
1) 예      315
2) 아니오    103
       count
q11_1
1.0       19
2.0       12
3.0       19
4.0       11
5.0       25
6.0       25
7.0       20
8.0       31
9.0       19
10.0      24
11.0      34
12.0      27
13.0      16
14.0       8
15.0       8
16.0       9
17.0       3
18.0       2
24.0       1
27.0       1
28.0       1
      count
q12
1) 예    500
        count
q13_1
1) 미술관    440
        count
q13_2
2) 박물관    500
           count
q13_3
3) 야구 경기장    363
           count
q13_4
4) 축구 경기장    266
        count
q13_5
5) 영화관    493
Empty DataFrame
Columns: [count]
Index: []
                       count
q14
1) 일년에 5회 이상 방문           77
2) 일년에 5회 미만 3회 이상 방문     82
3) 일년에 3회 미만 1회 이상 방문    172
4) 일년에 1회 미만 방문          169
                                   count
q15
1) 특정 전시물, 역사적 유물 등의 흥미로운 관람 목적      150
2) 유물과 전시물을 통해 역사와 문화에 대한 교육적인 목적    139
3) 가족, 친구, 연인과의 여가 및 휴식 목적           201
4) 자료 조사 및 연구 등 학습 목적                  8
5) 기타(구체적으로 응답해 주십시오)                  2
       count
q15_5
자녀교육       1
혼자 여가      1
                               count
q16
1) 전시 구성의 지루함 및 전시물에 대한 해설 부족    193
2) 다른 관람객으로 인한 혼잡 및 소음            63
3) 주차공간 부족 및 불편한 시설               38
4) 집에서 먼 거리를 이동해야 하는 시간적인 문제     166
5) 관람료, 프로그램 참여 비용 등의 금전적인 문제     37
6) 기타(구체적으로 응답해 주십시오)              3
                                count
q16_6
대체적으로 너무 어두움 그리고 청동거울 복원해논게 없음      1
비슷비슷한 진시물                           1
없음                                  1
          count
q17
2) 불만족       12
3) 보통       231
4) 만족       241
5) 매우 만족     16
        count
q18
1) 네      451
2) 아니요     49
                 count
q19
1) 일주일에 1-2회        69
2) 한 달에 1-2회       265
3) 거의 접한 적이 없음.    166
                 count
q20
1) 거의 매일 이용          8
2) 일주일에 1-2회 이용     28
3) 한 달에 1-2회 이용    103
4) 거의 이용하지 않음      361
                 count
q21
1) 매일 이용            12
2) 일주일에 3-4회 이용     27
3) 일주일에 1-2회 이용     30
4) 한 달에 1-2회 이용     75
5) 거의 이용하지 않음      171
                                                    count
q22
1) 현실에서 경험하기 어려운 다양한 상황을 가상으로 체험할 수 있는 게임 활동          191
2) 가상 세계에서 아바타를 통해 소통하고 관계를 맺을 수 있는 SNS 활동             67
3) 전시 및 회사 업무를 가상의 세계에서 수행하는 가상 오피스 관련 활동              34
4) 지역 축제 체험 및 대학교 입학식 등의 현실 세계의 활동을 가상의 세계를 통해 ...     48
5) 이용해 본 적 없음                                         160
                                              count
q23
1) 현실에서 경험하기 어려운 다양한 상황을 가상으로 체험할 수 있는 게임 활동     94
2) 재미있게 배우고 체험하는 메타버스 기반의 학습 및 교육 활동             78
3) 메타버스를 통해 친구들과 아바타로 소통하고, 같이 활동하는 친구 관계 활동     34
4) 아이돌 콘서트, 팬미팅 등 문화·공연 행사를 관람하는 활동               4
5) 이용해 본 적 없음                                   105
                                 count
q24
1) 낮은 해상도 및 속도로 현실을 표현하는 실재감 부족    107
2) 이용할 수 있는 콘텐츠의 부족 및 수준 낮은 콘텐츠    254
3) 상호 교류할 사용자의 부족                   98
4) 수집되고 이용되는 개인정보에 대한 보안 처리 미흡      41
                                count
q25
1) 장시간 이용에 따른 중독 증상 및 건강 악화 문제    133
2) 가상 세계에 안주한 현실 도피 문제            155
3) 디지털 세계의 정보 침해 및 악용 문제           94
4) 사이버 폭력 및 괴롭힘 심화 문제              49
5) 디지털 지식 및 환경에 따라 발생하는 불평등 문제     69
                                 count
q26
1) 현재 이미 완성되어 활성화되어 있는 서비스이다.       19
2) 계속 발전 중이며, 곧 서비스가 활성화 될 것이다.    348
3) 산업적 실체가 없는 마케팅용어에 불과하다.          73
4) 언론과 학계가 만든 허구적 개념이다.              6
5) 모르겠다.                            54
        count
q27
1) 네      172
2) 아니요    328
        count
q28
1) 네       65
2) 아니요    435
               count
q29
1) 전혀 중요하지 않다     16
2) 중요하지 않다        54
3) 보통이다          168
4) 중요하다          217
5) 매우 중요하다        45
               count
q30
1) 전혀 중요하지 않다      9
2) 중요하지 않다        29
3) 보통이다          168
4) 중요하다          240
5) 매우 중요하다        54
               count
q31
1) 전혀 중요하지 않다     14
2) 중요하지 않다        36
3) 보통이다          156
4) 중요하다          226
5) 매우 중요하다        68
               count
q32
1) 전혀 중요하지 않다      4
2) 중요하지 않다        16
3) 보통이다           95
4) 중요하다          234
5) 매우 중요하다       151
               count
q33
1) 전혀 중요하지 않다      4
2) 중요하지 않다        10
3) 보통이다           57
4) 중요하다          180
5) 매우 중요하다       249
               count
q34
1) 전혀 중요하지 않다      2
2) 중요하지 않다         9
3) 보통이다           80
4) 중요하다          185
5) 매우 중요하다       224
               count
q35
1) 전혀 중요하지 않다      4
2) 중요하지 않다        16
3) 보통이다          116
4) 중요하다          236
5) 매우 중요하다       128
               count
q36
1) 전혀 중요하지 않다      2
2) 중요하지 않다        12
3) 보통이다          107
4) 중요하다          226
5) 매우 중요하다       153
               count
q37
1) 전혀 중요하지 않다      6
2) 중요하지 않다        15
3) 보통이다          139
4) 중요하다          280
5) 매우 중요하다        60
               count
q38
1) 전혀 중요하지 않다      4
2) 중요하지 않다        18
3) 보통이다          133
4) 중요하다          264
5) 매우 중요하다        81
               count
q39
1) 전혀 중요하지 않다      4
2) 중요하지 않다        17
3) 보통이다          115
4) 중요하다          232
5) 매우 중요하다       132
               count
q40
1) 전혀 중요하지 않다      3
2) 중요하지 않다        11
3) 보통이다           96
4) 중요하다          250
5) 매우 중요하다       140
               count
q41
1) 전혀 중요하지 않다      8
2) 중요하지 않다        27
3) 보통이다          172
4) 중요하다          217
5) 매우 중요하다        76
               count
q42
1) 전혀 중요하지 않다      5
2) 중요하지 않다        18
3) 보통이다          131
4) 중요하다          231
5) 매우 중요하다       115
               count
q43
1) 전혀 중요하지 않다      2
2) 중요하지 않다        11
3) 보통이다           97
4) 중요하다          184
5) 매우 중요하다       206
                                                    count
q44_1
1) 시간과 장소에 대한 제약 없이 언제 어디서나 접속할 수 있는 편의성              240
2) 전시물 및 다른 사용자들과 소통을 통해 경험을 극대화하는 상호작용                58
3) 과거 역사 체험이나 우주 체험 등 현실 박물관에서는 불가능한 체험 활동            126
4) 서로 다른 박물관에 소장된 전시물을 한 번에 통합적으로 관람할 수 있는 기능          32
5) 현실 박물관과의 연계를 통한 교육적인 시너지 효과                         36
6) 게이미피케이션을 접목하여 사용자의 몰입도 및 교육 효과성 증가※게이미피케이션 :...      8
                                                    count
q44_2
1) 시간과 장소에 대한 제약 없이 언제 어디서나 접속할 수 있는 편의성               84
2) 전시물 및 다른 사용자들과 소통을 통해 경험을 극대화하는 상호작용                59
3) 과거 역사 체험이나 우주 체험 등 현실 박물관에서는 불가능한 체험 활동            170
4) 서로 다른 박물관에 소장된 전시물을 한 번에 통합적으로 관람할 수 있는 기능         102
5) 현실 박물관과의 연계를 통한 교육적인 시너지 효과                         64
6) 게이미피케이션을 접목하여 사용자의 몰입도 및 교육 효과성 증가※게이미피케이션 :...     21
                                                    count
q44_3
1) 시간과 장소에 대한 제약 없이 언제 어디서나 접속할 수 있는 편의성               56
2) 전시물 및 다른 사용자들과 소통을 통해 경험을 극대화하는 상호작용                56
3) 과거 역사 체험이나 우주 체험 등 현실 박물관에서는 불가능한 체험 활동             89
4) 서로 다른 박물관에 소장된 전시물을 한 번에 통합적으로 관람할 수 있는 기능         126
5) 현실 박물관과의 연계를 통한 교육적인 시너지 효과                        121
6) 게이미피케이션을 접목하여 사용자의 몰입도 및 교육 효과성 증가※게이미피케이션 :...     52
                                             count
q45_1
1) 제작사의 초기 플랫폼 제작에 필요한 높은 투자 비용                128
2) 사용하기 위해 고가의 VR 헤드셋 등의 별도의 단말기의 보유 필요        155
3) 박물관 구축 및 운영의 전문적인 기술 지식과 메타버스 기술 접목의 어려움     77
4) 몰입감 넘치는 전용 콘텐츠 제작의 어려움 및 지속적인 관리             77
5) 현실의 박물관이 보유하고 있는 저작권 문제 해결                   42
6) 사용자 유치 및 수익 창출을 통해 경제적 지속 가능성 확보             21
                                             count
q45_2
1) 제작사의 초기 플랫폼 제작에 필요한 높은 투자 비용                 71
2) 사용하기 위해 고가의 VR 헤드셋 등의 별도의 단말기의 보유 필요         94
3) 박물관 구축 및 운영의 전문적인 기술 지식과 메타버스 기술 접목의 어려움    108
4) 몰입감 넘치는 전용 콘텐츠 제작의 어려움 및 지속적인 관리            110
5) 현실의 박물관이 보유하고 있는 저작권 문제 해결                   63
6) 사용자 유치 및 수익 창출을 통해 경제적 지속 가능성 확보             54
                                             count
q45_3
1) 제작사의 초기 플랫폼 제작에 필요한 높은 투자 비용                 74
2) 사용하기 위해 고가의 VR 헤드셋 등의 별도의 단말기의 보유 필요         63
3) 박물관 구축 및 운영의 전문적인 기술 지식과 메타버스 기술 접목의 어려움     78
4) 몰입감 넘치는 전용 콘텐츠 제작의 어려움 및 지속적인 관리            121
5) 현실의 박물관이 보유하고 있는 저작권 문제 해결                   87
6) 사용자 유치 및 수익 창출을 통해 경제적 지속 가능성 확보             77
              count
q46
1) 전혀 그렇지 않다     17
2) 그렇지 않다       114
3) 보통이다         230
4) 그렇다          120
5) 매우 그렇다        19
              count
q47
1) 전혀 그렇지 않다      5
2) 그렇지 않다        69
3) 보통이다         238
4) 그렇다          156
5) 매우 그렇다        32
              count
q48
1) 전혀 그렇지 않다     26
2) 그렇지 않다       173
3) 보통이다         190
4) 그렇다           91
5) 매우 그렇다        20
              count
q49
1) 전혀 그렇지 않다     10
2) 그렇지 않다        80
3) 보통이다         190
4) 그렇다          171
5) 매우 그렇다        49
              count
q50
1) 전혀 그렇지 않다     20
2) 그렇지 않다       119
3) 보통이다         206
4) 그렇다          126
5) 매우 그렇다        29
              count
q51
1) 전혀 그렇지 않다     12
2) 그렇지 않다        67
3) 보통이다         203
4) 그렇다          183
5) 매우 그렇다        35
              count
q52
1) 전혀 그렇지 않다     19
2) 그렇지 않다       107
3) 보통이다         226
4) 그렇다          121
5) 매우 그렇다        27
              count
q53
1) 전혀 그렇지 않다      6
2) 그렇지 않다        91
3) 보통이다         193
4) 그렇다          181
5) 매우 그렇다        29
              count
q54
1) 전혀 그렇지 않다      9
2) 그렇지 않다        41
3) 보통이다         133
4) 그렇다          226
5) 매우 그렇다        91
              count
q55
1) 전혀 그렇지 않다     31
2) 그렇지 않다       123
3) 보통이다         203
4) 그렇다          114
5) 매우 그렇다        29
              count
q56
1) 전혀 그렇지 않다     15
2) 그렇지 않다        67
3) 보통이다         155
4) 그렇다          212
5) 매우 그렇다        51
              count
q57
1) 전혀 그렇지 않다      9
2) 그렇지 않다        38
3) 보통이다         149
4) 그렇다          227
5) 매우 그렇다        77
              count
q58
1) 전혀 그렇지 않다      3
2) 그렇지 않다        58
3) 보통이다         173
4) 그렇다          238
5) 매우 그렇다        28
              count
q59
1) 전혀 그렇지 않다      8
2) 그렇지 않다       117
3) 보통이다         174
4) 그렇다          171
5) 매우 그렇다        30
              count
q60
1) 전혀 그렇지 않다     10
2) 그렇지 않다       105
3) 보통이다         175
4) 그렇다          183
5) 매우 그렇다        27
              count
q61
1) 전혀 그렇지 않다     11
2) 그렇지 않다        78
3) 보통이다         184
4) 그렇다          178
5) 매우 그렇다        49
              count
q62
1) 전혀 그렇지 않다     10
2) 그렇지 않다        78
3) 보통이다         160
4) 그렇다          185
5) 매우 그렇다        67
              count
q63
1) 전혀 그렇지 않다      5
2) 그렇지 않다        70
3) 보통이다         137
4) 그렇다          209
5) 매우 그렇다        79
              count
q64
1) 전혀 그렇지 않다      7
2) 그렇지 않다        64
3) 보통이다         152
4) 그렇다          218
5) 매우 그렇다        59
              count
q65
1) 전혀 그렇지 않다     12
2) 그렇지 않다        75
3) 보통이다         157
4) 그렇다          202
5) 매우 그렇다        54
              count
q66
1) 전혀 그렇지 않다      8
2) 그렇지 않다        37
3) 보통이다         168
4) 그렇다          247
5) 매우 그렇다        40
              count
q67
1) 전혀 그렇지 않다     20
2) 그렇지 않다        51
3) 보통이다         248
4) 그렇다          154
5) 매우 그렇다        27
              count
q68
1) 전혀 그렇지 않다     11
2) 그렇지 않다        39
3) 보통이다         190
4) 그렇다          212
5) 매우 그렇다        48
              count
q69
1) 전혀 그렇지 않다     11
2) 그렇지 않다        42
3) 보통이다         166
4) 그렇다          219
5) 매우 그렇다        62
              count
q70
1) 전혀 그렇지 않다      2
2) 그렇지 않다        56
3) 보통이다         136
4) 그렇다          264
5) 매우 그렇다        42
              count
q71
1) 전혀 그렇지 않다      3
2) 그렇지 않다        53
3) 보통이다         143
4) 그렇다          240
5) 매우 그렇다        61
              count
q72
1) 전혀 그렇지 않다      7
2) 그렇지 않다        56
3) 보통이다         124
4) 그렇다          248
5) 매우 그렇다        65
              count
q73
1) 전혀 그렇지 않다      5
2) 그렇지 않다        40
3) 보통이다         125
4) 그렇다          261
5) 매우 그렇다        69
              count
q74
1) 전혀 그렇지 않다     71
2) 그렇지 않다       194
3) 보통이다         153
4) 그렇다           66
5) 매우 그렇다        16
              count
q75
1) 전혀 그렇지 않다     31
2) 그렇지 않다       109
3) 보통이다         218
4) 그렇다          104
5) 매우 그렇다        38
              count
q76
1) 전혀 그렇지 않다     62
2) 그렇지 않다       211
3) 보통이다         148
4) 그렇다           66
5) 매우 그렇다        13
              count
q77
1) 전혀 그렇지 않다     56
2) 그렇지 않다       200
3) 보통이다         179
4) 그렇다           49
5) 매우 그렇다        16
              count
q78
1) 전혀 그렇지 않다     56
2) 그렇지 않다       179
3) 보통이다         189
4) 그렇다           64
5) 매우 그렇다        12
              count
q79
1) 전혀 그렇지 않다     39
2) 그렇지 않다       147
3) 보통이다         212
4) 그렇다           90
5) 매우 그렇다        12
              count
q80
1) 전혀 그렇지 않다     79
2) 그렇지 않다       214
3) 보통이다         153
4) 그렇다           45
5) 매우 그렇다         9
              count
q81
1) 전혀 그렇지 않다     75
2) 그렇지 않다       201
3) 보통이다         162
4) 그렇다           54
5) 매우 그렇다         8
            count
q82
1) 지불의향 있음    126
2) 지불의향 없음    374
            count
q83
1) 지불의향 있음     45
2) 지불의향 없음     81
            count
q84
1) 지불의향 있음     71
2) 지불의향 없음    303
               count
q85
1) 지불의향 있음        73
2) 지불의향 전혀 없음    230
                                      count
q86_1
1) 박물관을 직접 방문하여 실제로 체감하는 것이 더 효율적이다.    130
                                  count
q86_2
2) 실제 학습에 거의 도움이 되지 않을 것으로 생각된다.     50
                                       count
q86_3
3) 현재 인터넷 검색 등으로 필요한 정보를 충분히 찾을 수 있다.     90
                                        count
q86_4
4) 실재감 있는 서비스 제공이 현재의 기술로는 부족하다고 생각한다.     74
                      count
q86_5
5) 추가적인 세금 납부가 부담된다.    112
                       count
q86_6
6) 기타(구체적으로 응답해 주십시오)      6
                           count
q86_6_A
세금으로 만들거면서 세금 걷는다는게 뭔 소리요      1
신뢰할 수 있는 정부로 바뀌면 고려할 것이다.      1
아이들과 함께 시간보내기가 어렵다             1
요금이 비싸다                        1
원할때만 이용하고 싶다                   1
흡연등  과태료를 대폭 올려 충당             1
        count
q87
1) 유형A     43
2) 유형B    220
3) 유형C    116
4) 유형D    121

        count
q88
1) 유형A     92
2) 유형B    280
3) 유형C     59
4) 유형D     69
        count
q89
1) 유형A     60
2) 유형B    160
3) 유형C    175
4) 유형D    105
        count
q90
1) 유형A    105
2) 유형B    248
3) 유형C     68
4) 유형D     79
        count
q91
1) 유형A     32
2) 유형B     91
3) 유형C    239
4) 유형D    138
        count
q92
1) 유형A    183
2) 유형B    173
3) 유형C     54
4) 유형D     90
        count
q93
1) 유형A     59
2) 유형B    233
3) 유형C     60
4) 유형D    148
        count
q94
1) 유형A    168
2) 유형B    155
3) 유형C     90
4) 유형D     87
        count
q95
1) 유형A    251
2) 유형B     78
3) 유형C    137
4) 유형D     34
        count
q96
1) 유형A     70
2) 유형B    175
3) 유형C    106
4) 유형D    149
       count
q97_1
1         61
2         36
3        166
4        211
5         22
6          4
       count
q98_1
0.0      276
1.0      119
2.0       42
3.0        1
       count
q98_2
0.0      237
1.0      160
2.0       39
3.0        3
       count
q98_3
0.0      347
1.0       75
2.0       17
       count
q98_4
0.0        1
1.0        8
2.0      348
3.0       47
4.0       29
5.0        5
        count
q98_t1
2.0        36
3.0       166
4.0       211
5.0        22
6.0         4
       count
q99_1
0          5
1          3
3          1
4          4
10         1
12        31
13         3
14       103
15         3
16       280
17         3
18        50
19         2
20         5
21         1
22         5
            count
q100
1) 자영업         26
2) 판매/서비스직     35
3) 사무/기술직     226
4) 전문직         44
5) 경영/관리직      26
6) 전업주부       115
7) 학생           3
8) 무직          10
9) 기타          15
        count
q100_9
공무          1
교사          1
사서          1
생산          1
생산직         2
아르바이트       1
영업          1
작품강사        1
파트타임        1
프리랜서        5
                   count
q101
1) 99만원 이하             3
10) 1,000만원 이상        40
2) 100만원-149만원 이하      2
3) 150만원-199만원 이하      9
4) 200만원-249만원 이하     32
5) 250만원-299만원 이하     39
6) 300만원-399만원 이하     67
7) 400만원-499만원 이하     79
8) 500만원-699만원 이하    139
9) 700만원-999만원 이하     90
                    count
q102
1) 소득 없음               46
10) 700만원-999만원 이하     51
11) 1,000만원 이상         23
2) 99만원 이하             29
3) 100만원-149만원 이하      18
4) 150만원-199만원 이하      22
5) 200만원-249만원 이하      44
6) 250만원-299만원 이하      55
7) 300만원-399만원 이하      67
8) 400만원-499만원 이하      73
9) 500만원-699만원 이하      72

In [73]:
df3.to_csv('bbb.csv',encoding='euc-kr')

In [72]:
df3

   category               name count              p_count
0        q1           1) 5000원   100                20.0%
1        q1           2) 7000원   100                20.0%
2        q1          3) 10000원   100                20.0%
3        q1          4) 15000원   100                20.0%
4        q1          5) 20000원   100                20.0%
..      ...                ...   ...                  ...
6      q102  5) 200만원-249만원 이하    44   8.799999999999999%
7      q102  6) 250만원-299만원 이하    55                11.0%
8      q102  7) 300만원-399만원 이하    67                13.4%
9      q102  8) 400만원-499만원 이하    73                14.6%
10     q102  9) 500만원-699만원 이하    72  14.399999999999999%

[599 rows x 4 columns]

In [6]:
df['q87'].value_counts()

q87
2) 유형B    220
4) 유형D    121
3) 유형C    116
1) 유형A     43
Name: count, dtype: int64

In [13]:
df[(df['q87']=='1) 유형A') & (df['q88']=='1) 유형A')]['q89']

6      4) 유형D
61     2) 유형B
99     4) 유형D
103    4) 유형D
109    2) 유형B
116    1) 유형A
125    4) 유형D
134    2) 유형B
161    4) 유형D
193    1) 유형A
206    2) 유형B
263    1) 유형A
313    4) 유형D
319    4) 유형D
348    4) 유형D
361    2) 유형B
401    4) 유형D
410    4) 유형D
438    1) 유형A
462    1) 유형A
Name: q89, dtype: object