In [1]:
import os
import win32com.client as win32

In [3]:
# 한글 프로그램 실행
hwp = win32.gencache.EnsureDispatch("HWPFrame.HwpObject")
hwp.RegisterModule("FilePathCheckDLL", "FilePathCheckerModule")

# 변환할 파일 경로 설정
getPath = r'C:\Users\user\OneDrive\바탕 화면\download'
files = [f for f in os.listdir(getPath) if f.endswith(('.hwp', '.hwpx'))]

PermissionError: [WinError 5] 액세스가 거부되었습니다: 'C:\\anaconda3\\Lib\\site-packages\\win32com\\gen_py\\7D2B6F3C-1D95-4E0C-BF5A-5EE564186FBCx0x1x0'

In [ ]:
# 일괄 변환 실행
for file in files:
    hwp.Open(os.path.join(getPath, file))
    pre, ext = os.path.splitext(file)
    
    # PDF 저장 설정
    hwp.HAction.GetDefault("FileSaveAs_S", hwp.HParameterSet.HFileOpenSave.HSet)
    hwp.HParameterSet.HFileOpenSave.filename = os.path.join(getPath, f"{pre}.pdf")
    hwp.HParameterSet.HFileOpenSave.Format = "PDF"
    hwp.HAction.Execute("FileSaveAs_S", hwp.HParameterSet.HFileOpenSave.HSet)

hwp.Quit()

In [3]:
import pandas as pd , numpy as np

In [4]:
file_name = r'C:\Users\user\OneDrive\바탕 화면\휴먼메트릭스\매출확인\2024.csv'

In [5]:
df = pd.read_csv(file_name)

In [6]:
df

,수요기관,용역명,계약금액,계약업체,계약방법,계약일자,계약기간,2순위,3순위,4순위,5순위,6순위,7순위,8순위
0,국가과학기술연구회,2024년 출연(연) 온라인 채용플랫폼 임차,"₩200,376,000",(주)마이다스인,수의계약,2024-01-01,계약체결후 366 일,단독응찰,NaN,NaN,NaN,NaN,NaN,NaN
1,한국수목원정원관리원,한국수목원정원관리원 제4차 신규직원 채용 대행 용역,"₩21,638,000",(사)한국능률협회,수의계약,2024-01-02,계약체결후 59 일,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,재단법인 서울특별시 사회서비스원,서울시사회서비스원 16차 직원채용 대행 위탁계약,"₩13,948,000",(주)사람인,수의계약,2024-01-02,계약체결후 45 일,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,제주특별자치도교육청,2024년 제1회 교육공무직원 채용 인성평가 위탁 용역,"₩16,879,500",주식회사 한국인재개발진흥원,수의계약,2024-01-02,착공후 12 일,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,한국고용노동교육원,2024년도 직원 채용 대행 용역,"₩55,000,000",주식회사 에이치알딥마인드,수의계약,2024-01-03,착공후 150 일,순위정보없음,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,0,NaN,NaN,NaN,일반경쟁,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
989,0,NaN,NaN,NaN,일반경쟁,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
990,0,NaN,NaN,NaN,일반경쟁,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
991,0,NaN,NaN,NaN,일반경쟁,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
992,0,NaN,NaN,NaN,일반경쟁,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df[df['수요기관']=='한국도로공사']

,수요기관,용역명,계약금액,계약업체,계약방법,계약일자,계약기간,2순위,3순위,4순위,5순위,6순위,7순위,8순위
235,한국도로공사,2024년 신입(인턴)사원 인재영입 대행 용역,"₩1,278,356,640",(주)휴노,일반경쟁,2024-03-15,NaN,株式會社 每日經濟新聞社,NaN,NaN,NaN,NaN,NaN,NaN
863,한국도로공사,[긴급]한국도로공사 온라인 전용채용관 구축운영 용역(2차),"₩177,832,332",(주)사람인,일반경쟁,2024-11-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
type(df['계약금액'])

pandas.core.series.Series

In [13]:
df['계약금액'].astype('int')

ValueError: invalid literal for int() with base 10: '₩200,376,000'